### ISSUE TITLE
Some viewmodel stuff should be core

### ISSUE THREAD

**Issue by antoninadert** [ManuelDeLeon/viewmodel-react-starter-meteor#1]
Like the viewmodelexplorer, an abstraction with universal router (integrate proto-starter?) 

To discuss what is actually useful

**Comment by ManuelDeLeon** [comment]
What's the end goal?

**Comment by antoninadert** [comment]
To have a clean starter pack

**Comment by ManuelDeLeon** [comment]
But what would be different? I don't understand the goal.

**Comment by antoninadert** [comment]
I want to refactor VM a little by separatin concerns in viewmodel. There would be a package for Validation features, one for state management (Mixins, shares, VM components...), one for debugging (ViewModel Explorer), one for isomorphic rendering, with as little boilerplate as possible, we would just import some stuff in the starter main.js

But this is additional work and I'm bad at unit testing
